name: animated_loading_widget
description: Beautiful story-based animated loaders for Flutter
version: 0.0.2

homepage: https://github.com/Sakshi-2508/animated_loading_widget
repository: https://github.com/Sakshi-2508/animated_loading_widget
issue_tracker: https://github.com/Sakshi-2508/animated_loading_widget/issues

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true